version: .{build}
os: Visual Studio 2015
init:
  - ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyy.M.d).$env:appveyor_build_number"
before_build:
- nuget restore src/CSharp.Script.sln
configuration:
  - Release
build:
  project: src/CSharp.Script.sln
  verbosity: minimal
after_build:
  - ps: nuget/build-appveyor.ps1
artifacts:
  - path: nuget/Releases/*
branches:
  only: 
    - master
skip_tags: true
deploy:
  tag: $(appveyor_build_version)
  release: CSharp.Script - $(appveyor_build_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: NuGet
  api_key:
    secure: qM2giZ/jAfZfWZCqrnLPw8Gii1tdfOR3qnk7p0Y7K1qg5tFLeVIFT4x5qyEe8mvi
  skip_symbols: false
  on:
    branch: master
cache:
  - src/packages